# Generated by Django 4.2.5 on 2023-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='c_features',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='c_luggage',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='c_mileage',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='car',
            name='c_seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='c_transmission',
            field=models.CharField(default='manual', max_length=100),
        ),
    ]
