# Generated by Django 4.2.5 on 2023-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_c_features_car_c_luggage_car_c_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='c_description',
            field=models.CharField(default='best car...', max_length=1000),
        ),
    ]
