# Generated by Django 4.2.5 on 2023-10-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_razorpay_order_id_car_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='c_price',
            field=models.IntegerField(default=1000),
        ),
    ]
